/**
 * \file
 *
 * \brief User board configuration template
 *
 */

#ifndef CONF_BOARD_H
#define CONF_BOARD_H

#define KEYBOARD_ROW_PORT IOPORT_PORTA

#define KEYBOARD_COLUMN_0_PIN IOPORT_CREATE_PIN(PORTB, 0)
#define KEYBOARD_COLUMN_1_PIN IOPORT_CREATE_PIN(PORTB, 1)
#define KEYBOARD_COLUMN_2_PIN IOPORT_CREATE_PIN(PORTB, 2)
#define KEYBOARD_COLUMN_3_PIN IOPORT_CREATE_PIN(PORTB, 3)
#define KEYBOARD_COLUMN_4_PIN IOPORT_CREATE_PIN(PORTC, 0)
#define KEYBOARD_COLUMN_5_PIN IOPORT_CREATE_PIN(PORTC, 1)
#define KEYBOARD_COLUMN_6_PIN IOPORT_CREATE_PIN(PORTC, 2)
#define KEYBOARD_COLUMN_7_PIN IOPORT_CREATE_PIN(PORTC, 3)
#define KEYBOARD_COLUMN_8_PIN IOPORT_CREATE_PIN(PORTD, 0)
#define KEYBOARD_COLUMN_9_PIN IOPORT_CREATE_PIN(PORTD, 1)
#define KEYBOARD_COLUMN_10_PIN IOPORT_CREATE_PIN(PORTD, 2)
#define KEYBOARD_COLUMN_11_PIN IOPORT_CREATE_PIN(PORTD, 3)

#define KEYBOARD_NUMBER_OF_COLUMNS 12
#define KEYBOARD_NUMBER_OF_ROWS 8

#define EEPROM_CS_PIN IOPORT_CREATE_PIN(PORTC, 4)
#define EEPROM_MOSI_PIN IOPORT_CREATE_PIN(PORTC, 5)
#define EEPROM_MISO_PIN IOPORT_CREATE_PIN(PORTC, 6)
#define EEPROM_SCK_PIN IOPORT_CREATE_PIN(PORTC, 7)

#define USB_DATA_MINUS_PIN IOPORT_CREATE_PIN(PORTD, 6)
#define USB_DATA_PLUS_PIN IOPORT_CREATE_PIN(PORTD, 7)

#define SWITCH_1_PIN IOPORT_CREATE_PIN(PORTR, 0)
#define SWITCH_2_PIN IOPORT_CREATE_PIN(PORTR, 1)
#define SWITCH_3_PIN IOPORT_CREATE_PIN(PORTE, 3)
#define SWITCH_4_PIN IOPORT_CREATE_PIN(PORTD, 4)
#define SWITCH_5_PIN IOPORT_CREATE_PIN(PORTD, 5)

#define LED_SHIFT_REGISTER_DS_PIN IOPORT_CREATE_PIN(PORTE, 0)
#define LED_SHIFT_REGISTER_SHCP_PIN IOPORT_CREATE_PIN(PORTE, 1)
#define LED_SHIFT_REGISTER_STCP_PIN IOPORT_CREATE_PIN(PORTE, 2)




#define CONF_BOARD_USB_PORT



#endif // CONF_BOARD_H
